### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by wuricong** [southliu/Southliu.github.io#1]
想咨询一下 你是通过什么方式将打包后的react项目部署到github pages上的？

**Comment by southliu** [comment]
我是使用vite创建react项目，再执行命令npm run build打包项目到dist，将dist的数据上传到你对应的xxx.github.io仓库下就好了．webpack同理．

**Comment by southliu** [comment]
react项目是这个：https://github.com/southliu/react-admin ，你可以参考着来。

**Comment by wuricong** [comment]
好的 感谢回答🙏
